from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from ..ai.controls import utcnow
from ..db import get_db
from ..models import AuditLog, Correction, Document, DocumentStatus, Extraction
from ..schemas import AcceptExtractionIn, AddExtractionIn, CorrectionIn
from ..services.review_service import (
    mark_extraction_accepted,
    refresh_document_review_status,
)
from ..services.template_service import get_template_definition, match_template_field
from ..services.validation_service import validate_value

router = APIRouter(tags=["extractions"])


@router.post("/documents/{document_id}/extractions")
def add_missing_extraction(
    document_id: int, payload: AddExtractionIn, db: Session = Depends(get_db)
):
    document = db.get(Document, document_id)
    if not document:
        raise HTTPException(status_code=404, detail="Document not found")
    if document.status == DocumentStatus.REJECTED.value:
        raise HTTPException(
            status_code=409,
            detail="Rejected documents are view-only and cannot be modified.",
        )

    field_name = payload.field_name.strip()
    value = payload.value.strip()
    if not field_name:
        raise HTTPException(status_code=400, detail="field_name is required")
    if not value:
        raise HTTPException(status_code=400, detail="value is required")

    standard_field_key = None
    template_key = None
    data_type = None
    required = False
    validation = {}
    stored_field_name = field_name

    if document.document_type_key:
        template = get_template_definition(document.document_type_key)
        match = match_template_field(template, field_name) if template else None
        if match:
            standard_field_key = match.key
            template_key = template.key if template else document.document_type_key
            data_type = match.data_type
            required = match.required
            validation = match.validation or {}
            stored_field_name = match.key
        else:
            stored_field_name = (
                f"suggested_extra_fields.{field_name.lower().replace(' ', '_')}"
            )
            data_type = "suggestion"

    validation_result = validate_value(
        stored_field_name, value, data_type, required, validation
    )
    accepted = not validation_result.requires_review

    extraction = Extraction(
        document_id=document_id,
        field_name=stored_field_name,
        template_key=template_key,
        standard_field_key=standard_field_key,
        data_type=data_type,
        required=required,
        extracted_value=value,
        confidence_score=1.0,
        source_snippet=(
            payload.source_snippet
            or "Manually added by reviewer; not present as an AI-extracted field."
        )[:500],
        ai_reasoning="Manually added by reviewer because this field was absent from the extracted fields. Not generated by AI.",
        validation_status=validation_result.status,
        validation_message=validation_result.message,
        validation_rule=validation_result.rule,
        needs_review=validation_result.requires_review,
        accepted=accepted,
        accepted_by=payload.added_by if accepted else None,
        accepted_at=utcnow() if accepted else None,
    )
    db.add(extraction)
    db.flush()

    refresh_document_review_status(db, document_id, actor=payload.added_by)
    db.add(
        AuditLog(
            document_id=document_id,
            action="field_manually_added",
            actor=payload.added_by,
            details=f'{stored_field_name}: manually added with value "{value}". Validation status: {validation_result.status}.',
        )
    )
    db.commit()
    return {"ok": True, "id": extraction.id, "document_status": document.status}


@router.patch("/extractions/{extraction_id}/correct")
def correct_extraction(
    extraction_id: int, payload: CorrectionIn, db: Session = Depends(get_db)
):
    extraction = db.scalar(
        select(Extraction)
        .where(Extraction.id == extraction_id)
        .options(selectinload(Extraction.corrections))
    )
    if not extraction:
        raise HTTPException(status_code=404, detail="Extraction not found")
    document = db.get(Document, extraction.document_id)
    if document and document.status == DocumentStatus.REJECTED.value:
        raise HTTPException(
            status_code=409,
            detail="Rejected documents are view-only and cannot be modified.",
        )

    old_field_name = extraction.field_name
    old_display_value = extraction.display_value
    old_review_confidence = extraction.review_confidence_score
    old_review_status = extraction.review_status

    template_field_locked = bool(extraction.standard_field_key)
    requested_field_name = (payload.field_name or extraction.field_name).strip()
    new_field_name = (
        extraction.field_name if template_field_locked else requested_field_name
    )
    new_display_value = (
        payload.corrected_value
        if payload.corrected_value is not None
        else old_display_value
    )

    if template_field_locked and requested_field_name != extraction.field_name:
        raise HTTPException(
            status_code=409,
            detail="Template field names are locked. Edit the value only so standardized client schemas remain consistent.",
        )
    if not new_field_name:
        raise HTTPException(status_code=400, detail="field_name cannot be empty")
    if new_display_value is None or not str(new_display_value).strip():
        raise HTTPException(status_code=400, detail="corrected_value cannot be empty")

    field_name_changed = new_field_name != old_field_name
    value_changed = new_display_value != old_display_value
    if (
        not field_name_changed
        and not value_changed
        and extraction.accepted
        and not extraction.needs_review
    ):
        return {
            "ok": True,
            "ai_confidence_score": extraction.confidence_score,
            "review_confidence_score": extraction.review_confidence_score,
            "review_status": extraction.review_status,
            "accepted": extraction.accepted,
            "needs_review": extraction.needs_review,
        }

    if field_name_changed:
        extraction.field_name = new_field_name
        db.add(
            AuditLog(
                document_id=extraction.document_id,
                action="field_name_changed",
                actor=payload.corrected_by,
                details=f'Extraction field name changed from "{old_field_name}" to "{new_field_name}".',
            )
        )

    if value_changed:
        db.add(
            Correction(
                extraction_id=extraction_id,
                old_value=old_display_value,
                corrected_value=new_display_value,
                corrected_by=payload.corrected_by,
            )
        )
        db.flush()

    validation_result = validate_value(
        extraction.standard_field_key or extraction.field_name,
        str(new_display_value),
        extraction.data_type,
        extraction.required,
        {},
    )
    extraction.validation_status = validation_result.status
    extraction.validation_message = validation_result.message
    extraction.validation_rule = validation_result.rule
    if validation_result.requires_review:
        extraction.accepted = False
        extraction.accepted_by = None
        extraction.accepted_at = None
        extraction.needs_review = True
    else:
        mark_extraction_accepted(extraction, payload.corrected_by)
    db.flush()

    new_review_confidence = extraction.review_confidence_score
    new_review_status = extraction.review_status
    refresh_document_review_status(
        db, extraction.document_id, actor=payload.corrected_by
    )

    details = []
    if field_name_changed:
        details.append(
            f'field name changed from "{old_field_name}" to "{new_field_name}"'
        )
    if value_changed:
        details.append(
            f'display value changed from "{old_display_value}" to "{new_display_value}"'
        )
    if not details:
        details.append(f'field "{extraction.field_name}" accepted without changes')

    db.add(
        AuditLog(
            document_id=extraction.document_id,
            action="field_reviewed",
            actor=payload.corrected_by,
            details=(
                f"{extraction.field_name}: " + "; ".join(details) + ". "
                f"AI confidence preserved at {round(extraction.confidence_score * 100)}%. "
                f"Review confidence changed from {round(old_review_confidence * 100)}% ({old_review_status}) "
                f"to {round(new_review_confidence * 100)}% ({new_review_status})."
            ),
        )
    )
    db.commit()
    return {
        "ok": True,
        "ai_confidence_score": extraction.confidence_score,
        "review_confidence_score": extraction.review_confidence_score,
        "review_status": extraction.review_status,
        "accepted": extraction.accepted,
        "needs_review": extraction.needs_review,
    }


@router.patch("/extractions/{extraction_id}/accept")
def accept_extraction(
    extraction_id: int, payload: AcceptExtractionIn, db: Session = Depends(get_db)
):
    extraction = db.scalar(
        select(Extraction)
        .where(Extraction.id == extraction_id)
        .options(selectinload(Extraction.corrections))
    )
    if not extraction:
        raise HTTPException(status_code=404, detail="Extraction not found")
    document = db.get(Document, extraction.document_id)
    if document and document.status == DocumentStatus.REJECTED.value:
        raise HTTPException(
            status_code=409,
            detail="Rejected documents are view-only and cannot be modified.",
        )

    old_review_status = extraction.review_status
    old_review_confidence = extraction.review_confidence_score

    validation_result = validate_value(
        extraction.standard_field_key or extraction.field_name,
        extraction.display_value,
        extraction.data_type,
        extraction.required,
        {},
    )
    extraction.validation_status = validation_result.status
    extraction.validation_message = validation_result.message
    extraction.validation_rule = validation_result.rule
    if validation_result.requires_review:
        extraction.accepted = False
        extraction.needs_review = True
        db.add(
            AuditLog(
                document_id=extraction.document_id,
                action="field_acceptance_blocked_by_validation",
                actor=payload.accepted_by,
                details=f"{extraction.field_name}: cannot be accepted because validation failed: {validation_result.message}",
            )
        )
    else:
        mark_extraction_accepted(extraction, payload.accepted_by)
    db.flush()

    refresh_document_review_status(
        db, extraction.document_id, actor=payload.accepted_by
    )
    db.add(
        AuditLog(
            document_id=extraction.document_id,
            action="field_accepted",
            actor=payload.accepted_by,
            details=(
                f'{extraction.field_name}: accepted display value "{extraction.display_value}". '
                f"Review confidence remained {round(old_review_confidence * 100)}%; "
                f"review status changed from {old_review_status} to {extraction.review_status}."
            ),
        )
    )
    db.commit()

    return {
        "ok": True,
        "accepted": extraction.accepted,
        "needs_review": extraction.needs_review,
        "review_confidence_score": extraction.review_confidence_score,
        "review_status": extraction.review_status,
    }


@router.delete("/extractions/{extraction_id}")
def delete_extraction(
    extraction_id: int, actor: str = "demo_user", db: Session = Depends(get_db)
):
    extraction = db.scalar(
        select(Extraction)
        .where(Extraction.id == extraction_id)
        .options(selectinload(Extraction.corrections))
    )
    if not extraction:
        raise HTTPException(status_code=404, detail="Extraction not found")

    document = db.get(Document, extraction.document_id)
    if document and document.status == DocumentStatus.REJECTED.value:
        raise HTTPException(
            status_code=409,
            detail="Rejected documents are view-only and cannot be modified.",
        )

    removable = (
        extraction.field_name.startswith("suggested_extra_fields.")
        or "Manually added by reviewer" in (extraction.ai_reasoning or "")
        or extraction.data_type == "suggestion"
    )
    if not removable:
        raise HTTPException(
            status_code=409,
            detail="Only suggested extra fields or manually added fields can be removed.",
        )

    document_id = extraction.document_id
    field_name = extraction.field_name
    display_value = extraction.display_value

    db.delete(extraction)
    db.flush()
    db.add(
        AuditLog(
            document_id=document_id,
            action="field_removed",
            actor=actor or "demo_user",
            details=f'{field_name}: removed from extracted fields. Previous display value was "{display_value}".',
        )
    )
    refresh_document_review_status(db, document_id, actor=actor or "demo_user")
    db.commit()
    return {"ok": True, "document_status": document.status if document else None}
